before_script:
  - |
    if [ ! -d /opt/build/machine-integration-frnt ] ; then
      mkdir -p /opt/build/machine-integration-frnt ;
    fi


stages:
  - build-test
  - build-prod
  - test
  - deploy

build-test:
  stage: build-test
  tags:
  - cnpmbuild
  script:
  - VER=`git log -n1|head -n1|cut -d " " -f2`
  - echo "Building Project Ver $VER"
  - sed -i 's/127.0.0.1:8181/172.18.8.69:8188/' ./src/request/request.js
  - cnpm install
  - cnpm run build
  - sonar-scanner  -Dsonar.projectKey=2019_machineintegrationfrnt  -Dsonar.sources=./src  -Dsonar.host.url=http://172.18.14.1:8001  -Dsonar.login=51bec2811fd8cc2ca39345bab5446cf57b651557
  - echo "Build success. Copy to dir..."
  - echo "File name $VER"
  - cd dist
  - tar czf ../$VER.tar.gz ./
  - cp -r ../$VER.tar.gz /opt/build/machine-integration-frnt/
  - VER=`git log -n1|head -n1|cut -d " " -f2`
  - cd ../
  - sed -i "s/VER/$VER/" Dockerfile
  - docker build -f ./Dockerfile -t 172.18.14.1:5000/machine-integration-frnt:$VER .
  - docker tag 172.18.14.1:5000/machine-integration-frnt:$VER 172.18.14.1:5000/machine-integration-frnt:test
  - docker push 172.18.14.1:5000/machine-integration-frnt:test
  only:
  - master
  
build-prod:
  stage: build-prod
  tags:
  - cnpmbuild
  script:
  - VER=`git log -n1|head -n1|cut -d " " -f2`
  - echo "Building Project Ver $VER"
  - sed -i 's/127.0.0.1/prodip/' ./src/request/request.js
  - cnpm install
  - cnpm run build
  - sonar-scanner  -Dsonar.projectKey=2019_machineintegrationfrnt  -Dsonar.sources=./src  -Dsonar.host.url=http://172.18.14.1:8001  -Dsonar.login=51bec2811fd8cc2ca39345bab5446cf57b651557
  - echo "Build success. Copy to dir..."
  - echo "File name $VER"
  - cd dist
  - tar czf ../$VER.tar.gz ./
  - cp -r ../$VER.tar.gz /opt/build/machine-integration-frnt/
  - VER=`git log -n1|head -n1|cut -d " " -f2`
  - cd ../
  - sed -i "s/VER/$VER/" Dockerfile
  - docker build -f ./Dockerfile -t 172.18.14.1:5000/machine-integration-frnt:$VER .
  - docker tag 172.18.14.1:5000/machine-integration-frnt:$VER 172.18.14.1:5000/machine-integration-frnt:latest
  - docker push 172.18.14.1:5000/machine-integration-frnt:latest
  only:
  - prod
  
test:
  stage: test
  tags:
  - java-test-8.69
  script:
  - docker pull 172.18.14.1:5000/machine-integration-frnt:test
  - DOCKERID=`docker ps |grep machine-integration-frnt |awk '{print $1}'`
  - docker stop $DOCKERID
  - docker rm $DOCKERID
  - docker run -d --name=machine-integration-frnt -p 80:80 172.18.14.1:5000/machine-integration-frnt:test
  only:
  - master

production:
  stage: deploy
  when: manual
  tags:
  - someprod-runner
  script:
  - docker pull 172.18.14.1:5000/machine-integration-frnt:latest
  - DOCKERID=`docker ps |grep machine-integration-frnt |awk '{print $1}'`
  - docker stop $DOCKERID
  - docker rm $DOCKERID
  - docker run -d --name=machine-integration-frnt -p 80:80 172.18.14.1:5000/machine-integration-frnt:latest
  only:
  - prod